// import axios from 'axios';
// import {useState} from 'react';

const mongoose = require('mongoose');
const Team = require('../models/team.model');
const Player = require('../models/player.model');

const teams = [
    {
        city: "New York",
        nickname: "Yankees",
        abbr: "NYY",
        league: "American",
        division: "AL East",
        games: 162,
        wins: 84,
        losses: 78,
        hex_color: "#003087",
        avatar: "https://purepng.com/public/uploads/medium/new-york-yankees-logo-blue-vlm.png",
        avg_ticket_cost: 58,
        payroll: 227854349,
        offense: {
            plate_appearances: 6059, 
            at_bats: 5458,
            runs_scored: 680,
            hits: 1378,
            homeruns: 183,
            walks: 475,
            strikeouts: 1188,
        },
        defense: {
            innings_pitched: 1428.1,
            hits_allowed: 1358,
            runs_allowed: 702,
            strikeouts_pitched: 1393,
            defensive_efficiency: 0.694,
        }
    },
    {
        city: "Boston",
        nickname: "Red Sox",
        abbr: "BOS",
        league: "American",
        division: "AL East",
        games: 162,
        wins: 93,
        losses: 69,
        hex_color: "#BD3039",
        avatar: "https://purepng.com/public/uploads/medium/boston-red-sox-logo-0ue.png",
        avg_ticket_cost: 105,
        payroll: 199864178,
        offense: {
            plate_appearances: 6320,
            at_bats: 5670,
            runs_scored: 878,
            hits: 1598,
            homeruns: 208,
            walks: 558,
            strikeouts: 1160,
        },
        defense: {
            innings_pitched: 1439.2,
            hits_allowed: 1342,
            runs_allowed: 694,
            strikeouts_pitched: 1362,
            defensive_efficiency: 0.695,
        }
    },
    {
        city: "Tampa Bay",
        nickname: "Rays",
        abbr: "TBR",
        league: "American",
        division: "AL East",
        games: 162,
        wins: 68,
        losses: 94,
        hex_color: "#8FBCE6",
        avatar: "https://purepng.com/public/uploads/medium/tampa-bay-rays-logo-if3.png",
        avg_ticket_cost: 64,
        payroll: 64120323,
        offense: {
            plate_appearances: 6046,
            at_bats: 5481,
            runs_scored: 672,
            hits: 1333,
            homeruns: 216,
            walks: 449,
            strikeouts: 1482,
        },
        defense: {
            innings_pitched: 1426.1,
            hits_allowed: 1395,
            runs_allowed: 713,
            strikeouts_pitched: 1357,
            defensive_efficiency: 0.687,
        }
    },
    {
        city: "Baltimore",
        nickname: "Orioles",
        abbr: "BAL",
        league: "American",
        division: "AL East",
        games: 162,
        wins: 89,
        losses: 73,
        hex_color: "#DF4601",
        avatar: "https://purepng.com/public/uploads/medium/baltimore-orioles-logo-7nq.png",
        avg_ticket_cost: 52,
        payroll: 147943713,
        offense: {
            plate_appearances: 6089,
            at_bats: 5524,
            runs_scored: 744,
            hits: 1413,
            homeruns: 253,
            walks: 468,
            strikeouts: 1324,
        },
        defense: {
            innings_pitched: 1432,
            hits_allowed: 1408,
            runs_allowed: 715,
            strikeouts_pitched: 1248,
            defensive_efficiency: 0.688,
        }
    },
    {
        city: "Toronto ",
        nickname: "Blue Jays",
        abbr: "TOR",
        league: "American",
        division: "AL East",
        games: 162,
        wins: 89,
        losses: 73,
        hex_color: "#134A8E",
        avatar: "https://purepng.com/public/uploads/medium/toronto-blue-jays-logo-dyd.png",
        avg_ticket_cost: 50,
        payroll: 140582027,
        offense: {
            plate_appearances: 6233,
            at_bats: 5479,
            runs_scored: 759,
            hits: 1358,
            homeruns: 221,
            walks: 632,
            strikeouts: 1362,
        },
        defense: {
            innings_pitched: 1459.1,
            hits_allowed: 1340,
            runs_allowed: 666,
            strikeouts_pitched: 1314,
            defensive_efficiency: 0.703,
        }
    },
    {
        city: "Cleveland",
        nickname: "Indians",
        abbr: "CLE",
        league: "American",
        division: "AL Central",
        games: 161,
        wins: 94,
        losses: 67,
        hex_color: "#E31937",
        avatar: "https://purepng.com/public/uploads/medium/cleveland-indians-logo-vko.png",
        avg_ticket_cost: 42,
        payroll: 98006899,
        offense: {
            plate_appearances: 6155,
            at_bats: 5484,
            runs_scored: 777,
            hits: 1435,
            homeruns: 185,
            walks: 531,
            strikeouts: 1246,
        },
        defense: {
            innings_pitched: 1445,
            hits_allowed: 1330,
            runs_allowed: 676,
            strikeouts_pitched: 1398,
            defensive_efficiency: 0.696,
        }
    },
    {
        city: "Kansas City",
        nickname: "Royals",
        abbr: "KCR",
        league: "American",
        division: "AL Central",
        games: 162,
        wins: 81,
        losses: 81,
        hex_color: "#004687",
        avatar: "https://purepng.com/public/uploads/medium/kansas-city-royals-logo-bn7.png",
        avg_ticket_cost: 65,
        payroll: 137606125,
        offense: {
            plate_appearances: 6052,
            at_bats: 5552,
            runs_scored: 675,
            hits: 1450,
            homeruns: 147,
            walks: 382,
            strikeouts: 1224,
        },
        defense: {
            innings_pitched: 1440,
            hits_allowed: 1433,
            runs_allowed: 712,
            strikeouts_pitched: 1287,
            defensive_efficiency: 0.687,
        }
    },
    {
        city: "Detroit",
        nickname: "Tigers",
        abbr: "DET",
        league: "American",
        division: "AL Central",
        games: 161,
        wins: 86,
        losses: 75,
        hex_color: "#0C2340",
        avatar: "https://purepng.com/public/uploads/medium/detroit-tigers-logo-tjq.png",
        avg_ticket_cost: 58,
        payroll: 199525500,
        offense: {
            plate_appearances: 6127,
            at_bats: 5526,
            runs_scored: 750,
            hits: 1476,
            homeruns: 211,
            walks: 493,
            strikeouts: 1303,
        },
        defense: {
            innings_pitched: 1428,
            hits_allowed: 1417,
            runs_allowed: 721,
            strikeouts_pitched: 1232,
            defensive_efficiency: 0.689,
        }
    },
    {
        city: "Chicago",
        nickname: "White Sox",
        abbr: "CWS",
        league: "American",
        division: "AL Central",
        games: 162,
        wins: 78,
        losses: 84,
        hex_color: "#27251F",
        avatar: "https://purepng.com/public/uploads/medium/chicago-white-sox-logo-vmj.png",
        avg_ticket_cost: 40,
        payroll: 115998667,
        offense: {
            plate_appearances: 6131,
            at_bats: 5550,
            runs_scored: 686,
            hits: 1428,
            homeruns: 168,
            walks: 455,
            strikeouts: 1285,
        },
        defense: {
            innings_pitched: 1446.2,
            hits_allowed: 1422,
            runs_allowed: 715,
            strikeouts_pitched: 1270,
            defensive_efficiency: 0.687,
        }
    },
    {
        city: "Minnesota ",
        nickname: "Twins",
        abbr: "MIN",
        league: "American",
        division: "AL Central",
        games: 162,
        wins: 59,
        losses: 103,
        hex_color: "#002B5C",
        avatar: "https://purepng.com/public/uploads/medium/minnesota-twins-logo-sd2.png",
        avg_ticket_cost: 57,
        payroll: 104591200,
        offense: {
            plate_appearances: 6245,
            at_bats: 5618,
            runs_scored: 722,
            hits: 1409,
            homeruns: 200,
            walks: 513,
            strikeouts: 1426,
        },
        defense: {
            innings_pitched: 1443,
            hits_allowed: 1617,
            runs_allowed: 889,
            strikeouts_pitched: 1191,
            defensive_efficiency: 0.662,
        }
    },
    {
        city: "Los Angeles",
        nickname: "Angels",
        abbr: "LAA",
        league: "American",
        division: "AL West",
        games: 162,
        wins: 74,
        losses: 88,
        hex_color: "#BA0021",
        avatar: "https://purepng.com/public/uploads/medium/los-angeles-angels-logo-wgl.png",
        avg_ticket_cost: 35,
        payroll: 166831190,
        offense: {
            plate_appearances: 6041,
            at_bats: 5431,
            runs_scored: 717,
            hits: 1410,
            homeruns: 156,
            walks: 471,
            strikeouts: 991,
        },
        defense: {
            innings_pitched: 1421.1,
            hits_allowed: 1480,
            runs_allowed: 727,
            strikeouts_pitched: 1136,
            defensive_efficiency: 0.685,
        }
    },
    {
        city: "Houston",
        nickname: "Astros",
        abbr: "HOU",
        league: "American",
        division: "AL West",
        games: 162,
        wins: 84,
        losses: 78,
        hex_color: "#EB6E1F",
        avatar: "https://purepng.com/public/uploads/medium/houston-astros-logo-xwi.png",
        avg_ticket_cost: 44,
        payroll: 96643000,
        offense: {
            plate_appearances: 6204,
            at_bats: 5545,
            runs_scored: 724,
            hits: 1367,
            homeruns: 198,
            walks: 554,
            strikeouts: 1452,
        },
        defense: {
            innings_pitched: 1468,
            hits_allowed: 1441,
            runs_allowed: 701,
            strikeouts_pitched: 1396,
            defensive_efficiency: 0.681,
        }
    },
    {
        city: "Seattle",
        nickname: "Mariners",
        abbr: "SEA",
        league: "American",
        division: "AL West",
        games: 162,
        wins: 86,
        losses: 76,
        hex_color: "#005C5C",
        avatar: "https://purepng.com/public/uploads/medium/seattle-mariners-logo-chf.png",
        avg_ticket_cost: 59,
        payroll: 144996858,
        offense: {
            plate_appearances: 6227,
            at_bats: 5583,
            runs_scored: 768,
            hits: 1446,
            homeruns: 223,
            walks: 506,
            strikeouts: 1288,
        },
        defense: {
            innings_pitched: 1457,
            hits_allowed: 1410,
            runs_allowed: 707,
            strikeouts_pitched: 1318,
            defensive_efficiency: 0.694,
        }
    },
    {
        city: "Oakland",
        nickname: "Athletics",
        abbr: "OAK",
        league: "American",
        division: "AL West",
        games: 162,
        wins: 69,
        losses: 93,
        hex_color: "#003831",
        avatar: "https://purepng.com/public/uploads/medium/oakland-athletics-logo-xl0.png",
        avg_ticket_cost: 55,
        payroll: 85823390,
        offense: {
            plate_appearances: 6022,
            at_bats: 5500,
            runs_scored: 653,
            hits: 1352,
            homeruns: 169,
            walks: 442,
            strikeouts: 1145,
        },
        defense: {
            innings_pitched: 1433.1,
            hits_allowed: 1459,
            runs_allowed: 761,
            strikeouts_pitched: 1188,
            defensive_efficiency: 0.685,
        }
    },
    {
        city: "Texas",
        nickname: "Rangers",
        abbr: "TEX",
        league: "American",
        division: "AL West",
        games: 162,
        wins: 95,
        losses: 67,
        hex_color: "#003278",
        avatar: "https://purepng.com/public/uploads/medium/texas-rangers-logos-4th.png",
        avg_ticket_cost: 49,
        payroll: 161246720,
        offense: {
            plate_appearances: 6089,
            at_bats: 5525,
            runs_scored: 765,
            hits: 1446,
            homeruns: 215,
            walks: 436,
            strikeouts: 1220,
        },
        defense: {
            innings_pitched: 1443,
            hits_allowed: 1441,
            runs_allowed: 757,
            strikeouts_pitched: 1154,
            defensive_efficiency: 0.692,
        }
    },
    {
        city: "New York",
        nickname: "Mets",
        abbr: "NYM",
        league: "National",
        division: "NL East",
        games: 162,
        wins: 87,
        losses: 75,
        hex_color: "#002D72",
        avatar: "https://purepng.com/public/uploads/medium/new-york-mets-logo-qeo.png",
        avg_ticket_cost: 72,
        payroll: 130612115,
        offense: {
            plate_appearances: 6115,
            at_bats: 5459,
            runs_scored: 671,
            hits: 1342,
            homeruns: 218,
            walks: 517,
            strikeouts: 1302,
        },
        defense: {
            innings_pitched: 1447,
            hits_allowed: 1397,
            runs_allowed: 617,
            strikeouts_pitched: 1396,
            defensive_efficiency: 0.678,
        }
    },
    {
        city: "Washington",
        nickname: "Nationals",
        abbr: "WAS",
        league: "National",
        division: "NL East",
        games: 162,
        wins: 95,
        losses: 67,
        hex_color: "#AB0003",
        avatar: "https://purepng.com/public/uploads/medium/washington-nationals-6gi.png",
        avg_ticket_cost: 51,
        payroll: 146686385,
        offense: {
            plate_appearances: 6201,
            at_bats: 5490,
            runs_scored: 763,
            hits: 1403,
            homeruns: 203,
            walks: 536,
            strikeouts: 1252,
        },
        defense: {
            innings_pitched: 1459.2,
            hits_allowed: 1272,
            runs_allowed: 612,
            strikeouts_pitched: 1476,
            defensive_efficiency: 0.7,
        }
    },
    {
        city: "Philadelphia",
        nickname: "Phillies",
        abbr: "PHI",
        league: "National",
        division: "NL East",
        games: 162,
        wins: 71,
        losses: 91,
        hex_color: "#E81828",
        avatar: "https://purepng.com/public/uploads/medium/st-louis-cardinals-logo-wyw.png",
        avg_ticket_cost: 59,
        payroll: 103346668,
        offense: {
            plate_appearances: 5992,
            at_bats: 5434,
            runs_scored: 610,
            hits: 1305,
            homeruns: 161,
            walks: 424,
            strikeouts: 1376,
        },
        defense: {
            innings_pitched: 1437,
            hits_allowed: 1468,
            runs_allowed: 796,
            strikeouts_pitched: 1299,
            defensive_efficiency: 0.681,
        }
    },
    {
        city: "Miami",
        nickname: "Marlins",
        abbr: "MIA",
        league: "National",
        division: "NL East",
        games: 161,
        wins: 79,
        losses: 82,
        hex_color: "#00A3E0",
        avatar: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Marlins_team_logo.svg/1200px-Marlins_team_logo.svg.png",
        avg_ticket_cost: 58,
        payroll: 70464500,
        offense: {
            plate_appearances: 6134,
            at_bats: 5547,
            runs_scored: 655,
            hits: 1460,
            homeruns: 128,
            walks: 447,
            strikeouts: 1213,
        },
        defense: {
            innings_pitched: 1435,
            hits_allowed: 1358,
            runs_allowed: 682,
            strikeouts_pitched: 1379,
            defensive_efficiency: 0.683,
        }
    },
    {
        city: "Atlanta",
        nickname: "Braves",
        abbr: "ATL",
        league: "National",
        division: "NL East",
        games: 161,
        wins: 68,
        losses: 93,
        hex_color: "#CE1141",
        avatar: "https://purepng.com/public/uploads/medium/atlanta-braves-logos-714.png",
        avg_ticket_cost: 36,
        payroll: 84821541,
        offense: {
            plate_appearances: 6192,
            at_bats: 5514,
            runs_scored: 649,
            hits: 1404,
            homeruns: 122,
            walks: 502,
            strikeouts: 1240,
        },
        defense: {
            innings_pitched: 1447.2,
            hits_allowed: 1414,
            runs_allowed: 779,
            strikeouts_pitched: 1227,
            defensive_efficiency: 0.692,
        }
    },
    {
        city: "Chicago",
        nickname: "Cubs",
        abbr: "CHC",
        league: "National",
        division: "NL Central",
        games: 162,
        wins: 103,
        losses: 58,
        hex_color: "#0E3386",
        avatar: "https://purepng.com/public/uploads/medium/chicago-cubs-logo-ekl.png",
        avg_ticket_cost: 125,
        payroll: 167444167,
        offense: {
            plate_appearances: 6335,
            at_bats: 5503,
            runs_scored: 808,
            hits: 1409,
            homeruns: 199,
            walks: 656,
            strikeouts: 1339,
        },
        defense: {
            innings_pitched: 1459.2,
            hits_allowed: 1125,
            runs_allowed: 556,
            strikeouts_pitched: 1441,
            defensive_efficiency: 0.728,
        }
    },
    {
        city: "Milwaukee",
        nickname: "Brewers",
        abbr: "MIL",
        league: "National",
        division: "NL Central",
        games: 162,
        wins: 73,
        losses: 89,
        hex_color: "#B6922E",
        avatar: "https://purepng.com/public/uploads/medium/milwaukee-brewers-logo-zk9.png",
        avg_ticket_cost: 43,
        payroll: 62964319,
        offense: {
            plate_appearances: 6061,
            at_bats: 5330,
            runs_scored: 671,
            hits: 1299,
            homeruns: 194,
            walks: 599,
            strikeouts: 1543,
        },
        defense: {
            innings_pitched: 1434.1,
            hits_allowed: 1450,
            runs_allowed: 733,
            strikeouts_pitched: 1175,
            defensive_efficiency: 0.68,
        }
    },
    {
        city: "Cincinnati",
        nickname: "Reds",
        abbr: "CIN",
        league: "National",
        division: "NL Central",
        games: 162,
        wins: 68,
        losses: 94,
        hex_color: "#C6011F",
        avatar: "https://purepng.com/public/uploads/medium/cincinnati-reds-logo-tms.png",
        avg_ticket_cost: 44,
        payroll: 93171452,
        offense: {
            plate_appearances: 6094,
            at_bats: 5487,
            runs_scored: 716,
            hits: 1403,
            homeruns: 164,
            walks: 452,
            strikeouts: 1284,
        },
        defense: {
            innings_pitched: 1442,
            hits_allowed: 1457,
            runs_allowed: 854,
            strikeouts_pitched: 1241,
            defensive_efficiency: 0.694,
        }
    },
    {
        city: "Pittsburgh",
        nickname: "Pirates",
        abbr: "PIT",
        league: "National",
        division: "NL Central",
        games: 161,
        wins: 78,
        losses: 83,
        hex_color: "#FDB827",
        avatar: "https://purepng.com/public/uploads/medium/pittsburgh-pirates-zcc.png",
        avg_ticket_cost: 59,
        payroll: 99960499,
        offense: {
            plate_appearances: 6261,
            at_bats: 5542,
            runs_scored: 729,
            hits: 1426,
            homeruns: 153,
            walks: 561,
            strikeouts: 1334,
        },
        defense: {
            innings_pitched: 1450.2,
            hits_allowed: 1490,
            runs_allowed: 758,
            strikeouts_pitched: 1232,
            defensive_efficiency: 0.676,
        }
    },
    {
        city: "St. Louis",
        nickname: "Cardinals",
        abbr: "STL",
        league: "National",
        division: "NL Central",
        games: 162,
        wins: 86,
        losses: 76,
        hex_color: "#C41E3A",
        avatar: "https://purepng.com/public/uploads/medium/st-louis-cardinals-logo-e4r.png",
        avg_ticket_cost: 49,
        payroll: 149186000,
        offense: {
            plate_appearances: 6223,
            at_bats: 5548,
            runs_scored: 779,
            hits: 1415,
            homeruns: 225,
            walks: 526,
            strikeouts: 1318,
        },
        defense: {
            innings_pitched: 1448.1,
            hits_allowed: 1432,
            runs_allowed: 712,
            strikeouts_pitched: 1290,
            defensive_efficiency: 0.679,
        }
    },
    {
        city: "San Francisco",
        nickname: "Giants",
        abbr: "SFG",
        league: "National",
        division: "NL West",
        games: 162,
        wins: 87,
        losses: 75,
        hex_color: "#FD5A1E",
        avatar: "https://purepng.com/public/uploads/medium/san-francisco-giants-ou9.png",
        avg_ticket_cost: 60,
        payroll: 171464943,
        offense: {
            plate_appearances: 6271,
            at_bats: 5565,
            runs_scored: 715,
            hits: 1437,
            homeruns: 130,
            walks: 572,
            strikeouts: 1107,
        },
        defense: {
            innings_pitched: 1460.1,
            hits_allowed: 1334,
            runs_allowed: 631,
            strikeouts_pitched: 1309,
            defensive_efficiency: 0.702,
        }
    },
    {
        city: "Los Angeles",
        nickname: "Dodgers",
        abbr: "LAD",
        league: "National",
        division: "NL West",
        games: 162,
        wins: 91,
        losses: 71,
        hex_color: "#005A9C",
        avatar: "https://logos-download.com/wp-content/uploads/2016/04/Los_Angeles_Dodgers_logo_blue-700x700.png",
        avg_ticket_cost: 38,
        payroll: 253639162,
        offense: {
            plate_appearances: 6164,
            at_bats: 5518,
            runs_scored: 725,
            hits: 1376,
            homeruns: 189,
            walks: 525,
            strikeouts: 1321,
        },
        defense: {
            innings_pitched: 1453,
            hits_allowed: 1266,
            runs_allowed: 638,
            strikeouts_pitched: 1510,
            defensive_efficiency: 0.699,
        }
    },
    {
        city: "Colorado",
        nickname: "Rockies",
        abbr: "COL",
        league: "National",
        division: "NL West",
        games: 162,
        wins: 75,
        losses: 87,
        hex_color: "#33006F",
        avatar: "https://purepng.com/public/uploads/medium/colorado-rockies-logo-v0m.png",
        avg_ticket_cost: 42,
        payroll: 113242571,
        offense: {
            plate_appearances: 6236,
            at_bats: 5614,
            runs_scored: 845,
            hits: 1544,
            homeruns: 204,
            walks: 494,
            strikeouts: 1330,
        },
        defense: {
            innings_pitched: 1429.1,
            hits_allowed: 1532,
            runs_allowed: 860,
            strikeouts_pitched: 1223,
            defensive_efficiency: 0.667,
        }
    },
    {
        city: "San Diego ",
        nickname: "Padres",
        abbr: "SDP",
        league: "National",
        division: "NL West",
        games: 162,
        wins: 68,
        losses: 94,
        hex_color: "#2F241D",
        avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/SD_Logo_Brown.svg/1200px-SD_Logo_Brown.svg.png",
        avg_ticket_cost: 56,
        payroll: 100547000,
        offense: {
            plate_appearances: 6001,
            at_bats: 5419,
            runs_scored: 686,
            hits: 1275,
            homeruns: 177,
            walks: 449,
            strikeouts: 1500,
        },
        defense: {
            innings_pitched: 1440,
            hits_allowed: 1425,
            runs_allowed: 770,
            strikeouts_pitched: 1222,
            defensive_efficiency: 0.687,
        }
    },
    {
        city: "Arizona",
        nickname: "Diamondbacks",
        abbr: "ARI",
        league: "National",
        division: "NL West",
        games: 162,
        wins: 69,
        losses: 93,
        hex_color: "#A71930",
        avatar: "https://purepng.com/public/uploads/medium/arizona-diamondbacks-logo-ogw.png",
        avg_ticket_cost: 50,
        payroll: 98657436,
        offense: {
            plate_appearances: 6260,
            at_bats: 5665,
            runs_scored: 752,
            hits: 1479,
            homeruns: 190,
            walks: 463,
            strikeouts: 1427,
        },
        defense: {
            innings_pitched: 1451.1,
            hits_allowed: 1563,
            runs_allowed: 890,
            strikeouts_pitched: 1318,
            defensive_efficiency: 0.665,
        }
    },
    {
        city: "League Average",
        nickname: "League Average",
        abbr: "AVG",
        league: "MLB",
        division: "MLB",
        games: 162,
        wins: 81,
        losses: 81,
        hex_color: "#747474",
        avatar: "https://purepng.com/public/uploads/medium/mlg-logo-without-name-asb.png",
        avg_ticket_cost: 55.83,
        payroll: 131261430,
        offense: {
            plate_appearances: 6153,
            at_bats: 5519,
            runs_scored: 725,
            hits: 1409,
            homeruns: 187,
            walks: 503,
            strikeouts: 1299,
        },
        defense: {
            innings_pitched: 1444,
            hits_allowed: 1409,
            runs_allowed: 725,
            strikeouts_pitched: 1299,
            defensive_efficiency: 0.688,
        }
    },
];

const players = [
    {
        name: "Babe Ruth",
        cumWar: {
            season01: -0.3,
            season02: 3.8,
            season03: 14.2,
            season04: 22.8,
            season05: 29.8,
            season06: 39.7,
            season07: 51.5,
            season08: 64.1,
            season09: 70.4,
            season10: 84.5,
            season11: 96.2,
            season12: 99.7,
            season13: 111.2,
            season14: 123.6,
            season15: 133.7,
            season16: 141.7,
            season17: 152.2,
            season18: 162.5,
            season19: 170.8,
            season20: 177.1,
            season21: 182.2,
            season22: 182.4,
        }
    },
    {
        name: "Barry Bonds",
        cumWar: {
            season01: 3.5,
            season02: 9.3,
            season03: 15.6,
            season04: 23.6,
            season05: 33.3,
            season06: 41.3,
            season07: 50.3,
            season08: 60.2,
            season09: 66.4,
            season10: 73.9,
            season11: 83.6,
            season12: 91.8,
            season13: 99.9,
            season14: 103.7,
            season15: 111.4,
            season16: 123.3,
            season17: 135.1,
            season18: 144.3,
            season19: 154.9,
            season20: 155.5,
            season21: 159.5,
            season22: 162.9,
        }
    },
    {
        name: "Mike Trout",
        cumWar: {
            season01: 0.5,
            season02: 11,
            season03: 20,
            season04: 27.6,
            season05: 37,
            season06: 47.5,
            season07: 54.1,
            season08: 64.3,
            season09: 72.6,
        }
    },
    {
        name: "Ken Griffey Jr",
        cumWar: {
            season01: 3.3,
            season02: 8.5,
            season03: 15.6,
            season04: 21.4,
            season05: 30.2,
            season06: 37.1,
            season07: 40.4,
            season08: 50.1,
            season09: 59.2,
            season10: 65.8,
            season11: 70.7,
            season12: 76.2,
            season13: 78.1,
            season14: 77.4,
            season15: 78.6,
            season16: 79.2,
            season17: 82.9,
            season18: 82.8,
            season19: 83.5,
            season20: 83.5,
            season21: 83.9,
            season22: 84.5,
            season23: 83.7,
        }
    },
    {
        name: "Cal Ripken Jr.",
        cumWar: {
            season01: -0.5,
            season02: 4.2,
            season03: 12.4,
            season04: 22.4,
            season05: 28,
            season06: 34.6,
            season07: 37.9,
            season08: 43.7,
            season09: 50.4,
            season10: 57.9,
            season11: 69.4,
            season12: 73.5,
            season13: 77.2,
            season14: 81.2,
            season15: 85.1,
            season16: 88.9,
            season17: 90.7,
            season18: 92.6,
            season19: 95.3,
            season20: 96.7,
            season21: 96.1,
        }
    },
    {
        name: "Willie Mays",
        cumWar: {
            season01: 4,
            season02: 5.3,
            season03: 15.9,
            season04: 25,
            season05: 32.6,
            season06: 40.9,
            season07: 51.2,
            season08: 59,
            season09: 68.5,
            season10: 77.2,
            season11: 87.7,
            season12: 98.3,
            season13: 109.3,
            season14: 120.5,
            season15: 129.5,
            season16: 133.9,
            season17: 140.2,
            season18: 143.3,
            season19: 148.5,
            season20: 154.8,
            season21: 155,
            season22: 156.6,
        }
    },
    {
        name: "Mickey Mantle",
        cumWar: {
            season01: 1.5,
            season02: 8,
            season03: 13.8,
            season04: 20.7,
            season05: 30.3,
            season06: 41.6,
            season07: 52.9,
            season08: 61.6,
            season09: 68.2,
            season10: 74.5,
            season11: 85,
            season12: 90.9,
            season13: 93.8,
            season14: 98.6,
            season15: 100.4,
            season16: 104,
            season17: 107.9,
            season18: 110.6,
        }
    },
    {
        name: "Alex Rodriguez",
        cumWar: {
            season01: -0.3,
            season02: -0.7,
            season03: 8.7,
            season04: 14.4,
            season05: 22.9,
            season06: 27.7,
            season07: 38.1,
            season08: 46.4,
            season09: 55.2,
            season10: 63.6,
            season11: 71.2,
            season12: 80.6,
            season13: 85.1,
            season14: 94.5,
            season15: 101.3,
            season16: 105.5,
            season17: 109.7,
            season18: 113.7,
            season19: 115.9,
            season20: 116.2,
            season21: 119.1,
            season22: 117.9,
        }
    },
    {
        name: "Lou Gehrig",
        cumWar: {
            season01: 0.4,
            season02: 0.6,
            season03: 3.8,
            season04: 10.6,
            season05: 22.4,
            season06: 31.8,
            season07: 39.4,
            season08: 49,
            season09: 57.8,
            season10: 65.7,
            season11: 72.6,
            season12: 83,
            season13: 91.7,
            season14: 100.8,
            season15: 108.5,
            season16: 112.8,
            season17: 112.5,
        }
    },
    {
        name: "Ted Williams",
        cumWar: {
            season01: 6.7,
            season02: 13,
            season03: 23.6,
            season04: 34.2,
            season05: 45.1,
            season06: 55,
            season07: 63.5,
            season08: 72.6,
            season09: 76.5,
            season10: 83.7,
            season11: 84,
            season12: 86,
            season13: 93.8,
            season14: 100.7,
            season15: 106.8,
            season16: 116.5,
            season17: 120.5,
            season18: 120.3,
            season19: 123.3,
        }
    },
];

mongoose.connect("mongodb://localhost/baseballdb10", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
})
    .then(() => console.log("Established a connection to the database"))
    .catch(err => console.log("Something went wrong when connecting to the database!", err));

var db = mongoose.connection;


db.collections.players.countDocuments({}, function( err, count ){
    if(count === 0){
        players.map(data => {
            const player = new Player(data);
            player.save();
        });
    };
})
db.collections.teams.countDocuments({}, function( err, count ){
    if(count === 0){
        teams.map(data => {
            const team = new Team(data);
            team.save();
        });
    };
})
